id: P005604
initial_creation_type: ocr
source_metadata:
  id: bdr:W30535
  title: རས་ཆུང་རྡོ་རྗེ་གྲགས་པའི་རྣམ་ཐར
  author: ''
  volumes:
    683a19722d0942cd8d3177dde80c52f7:
      image_group_id: I6451
      title: ''
      volume_number: 1
      total_pages: 1524
      base_file: v001.txt
